### ISSUE TITLE
Skodaconnect library has new version 1.1.19

### ISSUE THREAD

**Issue by JongsmaSimon** [flopp999/SkodaConnect-Domoticz#5]
Skodaconnect library has new version 1.1.19 I am assuming for changes in API. so I think requirements.txt should updated to that and this module tested.
I tried just that and that gave the following result:
2022-02-24 14:48:10.686 Enyaq: Traceback (most recent call last):
2022-02-24 14:48:10.686 File "/home/pi/domoticz/plugins/SkodaConnect-Domoticz/plugin.py", line 69, in main
2022-02-24 14:48:10.686 await connection.doLogin()
2022-02-24 14:48:10.686 File "/usr/local/lib/python3.7/dist-packages/skodaconnect/connection.py", line 136, in doLogin
2022-02-24 14:48:10.686 return await self._authorize('skoda')
2022-02-24 14:48:10.686 File "/usr/local/lib/python3.7/dist-packages/skodaconnect/connection.py", line 197, in _authorize
2022-02-24 14:48:10.686 raise SkodaException('Missing "location" header')
2022-02-24 14:48:10.686 skodaconnect.exceptions.SkodaException: Missing "location" header
2022-02-24 14:48:10.686
2022-02-24 14:48:10.686 Enyaq: <class 'skodaconnect.exceptions.SkodaException'>
2022-02-24 14:48:10.686 Enyaq: Something went wrong when access Skoda API

**Comment by flopp999** [comment]
I now tried using plugin version 0.28 and SkodaConnect 1.1.19 and I do not get any errors.

**Comment by JongsmaSimon** [comment]
Did a new pull & restarted Domoticz: now it works OK
