### ISSUE TITLE
Install issues with Domoticz, please help

### ISSUE THREAD

**Issue by EHVBspotter** [flopp999/SkodaConnect-Domoticz#8]
Hi I try to install the plugin with Domoticz Beta Version: 2022.2 (build 14958)) but I got errors while loading the plugin
Please can you help me with this?

see here a part of the log of Domoticz looping these errors

2023-01-14 20:35:56.464 Error: My Enyaq: Call to function 'onHeartbeat' failed, exception details:
2023-01-14 20:35:56.466 Error: My Enyaq: Traceback (most recent call last):
2023-01-14 20:35:56.466 Error: My Enyaq: File "/home/pi/domoticz/plugins/SkodaConnect-Domoticz/plugin.py", line 596, in onHeartbeat
2023-01-14 20:35:56.466 Error: My Enyaq: _plugin.onHeartbeat()
2023-01-14 20:35:56.466 Error: My Enyaq: File "/home/pi/domoticz/plugins/SkodaConnect-Domoticz/plugin.py", line 140, in onHeartbeat
2023-01-14 20:35:56.466 Error: My Enyaq: asyncio.run(main())
2023-01-14 20:35:56.466 Error: My Enyaq: File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
2023-01-14 20:35:56.466 Error: My Enyaq: return loop.run_until_complete(main)
2023-01-14 20:35:56.466 Error: My Enyaq: File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
2023-01-14 20:35:56.466 Error: My Enyaq: return future.result()
2023-01-14 20:35:56.466 Error: My Enyaq: File "/home/pi/domoticz/plugins/SkodaConnect-Domoticz/plugin.py", line 64, in main
2023-01-14 20:35:56.466 Error: My Enyaq: async with ClientSession(headers={'Connection': 'keep-alive'}) as session:
2023-01-14 20:35:56.467 Error: My Enyaq: NameError: name 'ClientSession' is not defined
2023-01-14 20:36:06.512 Error: My Enyaq: Call to function 'onHeartbeat' failed, exception details:
2023-01-14 20:36:06.514 Error: My Enyaq: Traceback (most recent call last):
2023-01-14 20:36:06.514 Error: My Enyaq: File "/home/pi/domoticz/plugins/SkodaConnect-Domoticz/plugin.py", line 596, in onHeartbeat
2023-01-14 20:36:06.514 Error: My Enyaq: _plugin.onHeartbeat()
2023-01-14 20:36:06.514 Error: My Enyaq: File "/home/pi/domoticz/plugins/SkodaConnect-Domoticz/plugin.py", line 140, in onHeartbeat

SkodaConnect.log
2023-01-14 20:41:15.058384 Ping
2023-01-14 20:41:15.495622 Internet is OK
2023-01-14 20:41:25.054083 ===heartbeat===
2023-01-14 20:41:25.056547 Entered CheckInternet
2023-01-14 20:41:25.057847 Ping
2023-01-14 20:41:25.476532 Internet is OK
2023-01-14 20:41:35.082167 ===heartbeat===
2023-01-14 20:41:35.084575 Entered CheckInternet
2023-01-14 20:41:35.085586 Ping
2023-01-14 20:41:35.533292 Internet is OK
2023-01-14 20:41:45.079032 ===heartbeat===
2023-01-14 20:41:45.081412 Entered CheckInternet
2023-01-14 20:41:45.082771 Ping
2023-01-14 20:41:45.532318 Internet is OK

**Comment by flopp999** [comment]
Hi sorry but I don't use Domoticz anymore so I have no possibility to help you

**Comment by EHVBspotter** [comment]
Oke, that is a shame. but do you have any idea where to start to debug? tips and hints?
